---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgBZba5bdTD/gPklLzWFR2F87QQgkr/Z5Xtcm/vTQgFSZZnzEFBNzl06kBIrUKIIwRJOCHNQvq3BJTmmawJ47IAHl1Osaf8tocSbtDa4K0LyGbBgw+v/6xt+j7lNxn23CuEwkupOs9kMiXO5mg41JB+Nd2fTHvGTpG2DYcq+sQrFmnfKtyRAb85DMDYT2HlgjJPwpKnUDR2fZmCS2KPHABelh/xGI64ehvZUAPXk2AMp6dSadaH9Esur+I3qVFVsO54sdLSRo66rEkSJ+ar/ZTrkZkruntIungBzzu2AqRPttnfL/cy9E22VN8lM//FQYlTTubph+WTajRY7SegfahT2096nWLHiAFpOEJ5X4Q0+G9V5IRufBKztHgyM/YdQuVn3bCGZevbgwWtHi9k+9dJ/Ye1/ish5bMuN+Eb6Tunstaw9jP4gRyJkWiWztHJR8Qk5MqA9QPVGeBS9NQJY7or8rGFICtWOh0jQemxwMqfkHNf+XIJj8jTI8d3F7novNPvqPOwK0wxnuhXk2Ctj1V/odPvU75kodp2DNK+t0r3mNUS9JA/Yj7B+p6cDjavFkxMS1LavoZstDJA3UvtToiTcXxyeHwPMnJ/j7fltSveiORQi2uNB7euZDO1uzpqDwqDX6bQN53xL63xSfculDt8sSEO6ZffNBx+7B+JxaGM7gCxUDNXT7NzAjt20Gods47RXDOwVcQ1vAg==
    username: AgDTh33FdvwzlQGqYNUSz6+Rxi+Y+pQ83XMRDsrwlCsBmDQWFSIr99eiLniikzpwg4aTjt+Nm47yw08pQFju8hhWAL2Gm5a0xIGmDGszx4KqMuq2v9+tC/6VNV5xLgf/23fzwHZibgAzXm/DcFNfYAHq7aoyzEwaa+IqBlYMcDQIgZTbU+eUyDAZhKxdWwy5iKpv1YX0KIjKWPaTjVG+cdNwExqoGS0K70BK2c3tMwllAxWO68YvvNtaFRsARUgOCnx8ElmN2I9F/vuetYSpMSQokiOBsEz6O53jeU/14C0OV1DAvIfc9erBkZNaDPxAAedgFuXdoey5eVXgBOozqE4VSA55kvvdXuSBpnw0CoCpLIfgoVokk+KpU3mA6zP7U9Hb+ltP2MQmFjKq5X8deULDL1Bp7uFqSWdDcsfErPO4ObeKgDjaLtPfaCCGX68eiSKJrUCtbYcjx9GrCmrBECQRSMn29UNs3g2Z8aLBK8k4NXbC70qD8BGRdENb2NydDJXey5sxREXbcNv9QtwaYsKlU4SVtmAuGnqURFBeP2KCAjQ4sNh0Om2tmWOKiYGsN8qUyLmjusugNsky06D98KqB92vvZvR+EJPZ7jSOFy7EwrSBwdCoTDqGoxEEFwBGcTqzPxHi/vfniZ//PYU4rAE7YHaKNEAMdLUdAUEkHFIQh59fnhU98W4TxoGH+xgicg7kdBBsR6im/bExAw==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
